-- 工数管理β版の監査ログを追加する、データ非破壊のSQLです。
--
-- このSQLが行うこと:
-- - 工数と主要マスタの追加・更新・削除を public.audit_log に保存します。
-- - 削除前の行全体を old_data に残すため、管理者が手動復元を検討できます。
-- - 既存の工数・マスタは更新も削除もしません。
--
-- 実行前:
-- 1. Supabase Dashboard または CLI でバックアップを取得する。
-- 2. SUPABASE_AUTH_PERMISSION_SETUP.sql と SUPABASE_AUTH_RLS_POLICIES.sql が実行済みであることを確認する。
-- 3. まずテスト環境で実行し、追加・更新・削除の監査行が記録されることを確認する。
--
-- 注意:
-- - このSQLは論理削除へ切り替えるものではありません。
-- - 本番での復元は BETA_BACKUP_RECOVERY.md に従い、先に別プロジェクトで検証してください。

begin;

create or replace function public.current_company_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select company_id
  from public.user_profiles
  where auth_user_id = auth.uid()
    and is_active = true
  limit 1
$$;

revoke all on function public.current_company_id() from public;
grant execute on function public.current_company_id() to authenticated;

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  company_id uuid references public.company_master(id) on delete set null,
  actor_user_id uuid,
  action text not null check (action in ('insert', 'update', 'delete')),
  table_name text not null,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_log_created_at_idx
  on public.audit_log(created_at desc);

create index if not exists audit_log_target_idx
  on public.audit_log(table_name, record_id, created_at desc);

create index if not exists audit_log_company_id_idx
  on public.audit_log(company_id, created_at desc);

alter table public.audit_log enable row level security;

revoke all on public.audit_log from anon;
revoke insert, update, delete on public.audit_log from authenticated;
grant select on public.audit_log to authenticated;

drop policy if exists "audit_log_admin_select" on public.audit_log;
create policy "audit_log_admin_select"
on public.audit_log
for select
to authenticated
using (
  public.current_app_role() = 'system_admin'
  or (
    public.current_app_role() = 'company_admin'
    and company_id = public.current_company_id()
  )
);

create or replace function public.capture_beta_audit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_json jsonb;
  new_json jsonb;
  company_text text;
  company_value uuid;
  record_value text;
begin
  old_json := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  new_json := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;

  company_text := coalesce(new_json ->> 'company_id', old_json ->> 'company_id');
  if nullif(company_text, '') is not null then
    begin
      company_value := company_text::uuid;
    exception when invalid_text_representation then
      company_value := null;
    end;
  end if;

  if company_value is null then
    company_value := public.current_company_id();
  end if;

  record_value := coalesce(new_json ->> 'id', old_json ->> 'id');

  insert into public.audit_log (
    company_id,
    actor_user_id,
    action,
    table_name,
    record_id,
    old_data,
    new_data
  )
  values (
    company_value,
    auth.uid(),
    lower(tg_op),
    tg_table_name,
    record_value,
    old_json,
    new_json
  );

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end
$$;

revoke all on function public.capture_beta_audit() from public;

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'work_logs',
    'worker_master',
    'work_type_master',
    'seiban_master',
    'billing_company_master',
    'rate_master'
  ]
  loop
    if to_regclass(format('public.%I', target_table)) is not null then
      execute format(
        'drop trigger if exists beta_audit_trigger on public.%I',
        target_table
      );
      execute format(
        'create trigger beta_audit_trigger after insert or update or delete on public.%I for each row execute function public.capture_beta_audit()',
        target_table
      );
    end if;
  end loop;
end
$$;

notify pgrst, 'reload schema';

commit;

-- 実行後の確認例（データは変更しません）
-- select id, created_at, actor_user_id, action, table_name, record_id
-- from public.audit_log
-- order by id desc
-- limit 50;
